/**
 * The manifest's labels in the seven languages beside English, keyed by the
 * English label (see `labels.ts`). Drafts until a native speaker has read
 * them (`src/i18n/review-status.json`).
 */
import type { Translation } from "./labels.ts";

export const WORDS: Record<string, Translation> = {
  "A later email took its place": { "de-DE": "Eine spätere E-Mail hat sie ersetzt", "fr-FR": "Un e-mail ultérieur l’a remplacé", "da-DK": "En senere mail erstattede den", "cs-CZ": "Nahradil ho pozdější e-mail", "ar-EG": "حلّت محلها رسالة لاحقة", "zh-CN": "已被之后的邮件取代", "zh-TW": "已被之後的郵件取代" },
  "About line": { "de-DE": "Über uns", "fr-FR": "Présentation", "da-DK": "Om os", "cs-CZ": "O nás", "ar-EG": "نبذة", "zh-CN": "简介", "zh-TW": "簡介" },
  "Address": { "de-DE": "Adresse", "fr-FR": "Adresse", "da-DK": "Adresse", "cs-CZ": "Adresa", "ar-EG": "العنوان", "zh-CN": "地址", "zh-TW": "地址" },
  "Allergens": { "de-DE": "Allergene", "fr-FR": "Allergènes", "da-DK": "Allergener", "cs-CZ": "Alergeny", "ar-EG": "مسببات الحساسية", "zh-CN": "过敏原", "zh-TW": "過敏原" },
  "Area": { "de-DE": "Gegend", "fr-FR": "Quartier", "da-DK": "Område", "cs-CZ": "Oblast", "ar-EG": "المنطقة", "zh-CN": "区域", "zh-TW": "區域" },
  "Booked": { "de-DE": "Gebucht", "fr-FR": "Réservé", "da-DK": "Booket", "cs-CZ": "Rezervováno", "ar-EG": "محجوز", "zh-CN": "已预订", "zh-TW": "已預訂" },
  "Called": { "de-DE": "Angerufen", "fr-FR": "Appelé", "da-DK": "Ringet op", "cs-CZ": "Zavoláno", "ar-EG": "تم الاتصال", "zh-CN": "已致电", "zh-TW": "已致電" },
  "Cancel note": { "de-DE": "Stornohinweis", "fr-FR": "Note d’annulation", "da-DK": "Annulleringsnote", "cs-CZ": "Poznámka ke zrušení", "ar-EG": "ملاحظة الإلغاء", "zh-CN": "取消备注", "zh-TW": "取消備註" },
  "Cancelled": { "de-DE": "Storniert", "fr-FR": "Annulée", "da-DK": "Annulleret", "cs-CZ": "Zrušeno", "ar-EG": "ملغى", "zh-CN": "已取消", "zh-TW": "已取消" },
  "Cancelled by": { "de-DE": "Storniert von", "fr-FR": "Annulée par", "da-DK": "Annulleret af", "cs-CZ": "Zrušil(a)", "ar-EG": "ألغاه", "zh-CN": "取消人", "zh-TW": "取消人" },
  "Cancelled by the customer": { "de-DE": "Vom Gast storniert", "fr-FR": "Annulée par le client", "da-DK": "Annulleret af gæsten", "cs-CZ": "Zrušeno hostem", "ar-EG": "ألغاه الزبون", "zh-CN": "顾客已取消", "zh-TW": "顧客已取消" },
  "Cancelled online by the customer": { "de-DE": "Vom Gast online storniert", "fr-FR": "Annulée en ligne par le client", "da-DK": "Annulleret online af gæsten", "cs-CZ": "Zrušeno hostem online", "ar-EG": "ألغاه الزبون عبر الإنترنت", "zh-CN": "顾客在线取消", "zh-TW": "顧客線上取消" },
  "Cancelled: another reason": { "de-DE": "Storniert: anderer Grund", "fr-FR": "Annulée : autre raison", "da-DK": "Annulleret: en anden grund", "cs-CZ": "Zrušeno: jiný důvod", "ar-EG": "أُلغي: سبب آخر", "zh-CN": "已取消：其他原因", "zh-TW": "已取消：其他原因" },
  "Cancelled: as the customer asked": { "de-DE": "Storniert: auf Wunsch des Gasts", "fr-FR": "Annulée : à la demande du client", "da-DK": "Annulleret: som gæsten bad om", "cs-CZ": "Zrušeno: na přání hosta", "ar-EG": "أُلغي: بناءً على طلب الزبون", "zh-CN": "已取消：应顾客要求", "zh-TW": "已取消：應顧客要求" },
  "Cancelled: not ready by closing": { "de-DE": "Storniert: bis Ladenschluss nicht fertig", "fr-FR": "Annulée : pas prête avant la fermeture", "da-DK": "Annulleret: ikke klar før lukketid", "cs-CZ": "Zrušeno: nehotové do zavírací doby", "ar-EG": "أُلغي: لم يجهز قبل الإغلاق", "zh-CN": "已取消：打烊前未做好", "zh-TW": "已取消：打烊前未做好" },
  "Cancelled: something ran out": { "de-DE": "Storniert: etwas ist ausgegangen", "fr-FR": "Annulée : un produit a manqué", "da-DK": "Annulleret: noget slap op", "cs-CZ": "Zrušeno: něco došlo", "ar-EG": "أُلغي: نفد شيء", "zh-CN": "已取消：有食材用完了", "zh-TW": "已取消：有食材用完了" },
  "Cancelled: the kitchen was too busy": { "de-DE": "Storniert: die Küche war zu voll", "fr-FR": "Annulée : cuisine trop chargée", "da-DK": "Annulleret: køkkenet havde for travlt", "cs-CZ": "Zrušeno: kuchyně byla přetížená", "ar-EG": "أُلغي: المطبخ مشغول جدًا", "zh-CN": "已取消：厨房太忙", "zh-TW": "已取消：廚房太忙" },
  "Card": { "de-DE": "Karte", "fr-FR": "Carte", "da-DK": "Kort", "cs-CZ": "Karta", "ar-EG": "بطاقة", "zh-CN": "刷卡", "zh-TW": "刷卡" },
  "Cash": { "de-DE": "Bar", "fr-FR": "Espèces", "da-DK": "Kontant", "cs-CZ": "Hotově", "ar-EG": "نقدًا", "zh-CN": "现金", "zh-TW": "現金" },
  "Categories": { "de-DE": "Kategorien", "fr-FR": "Catégories", "da-DK": "Kategorier", "cs-CZ": "Kategorie", "ar-EG": "الفئات", "zh-CN": "分类", "zh-TW": "分類" },
  "Chosen option": { "de-DE": "Gewählte Option", "fr-FR": "Option choisie", "da-DK": "Valgt tilvalg", "cs-CZ": "Zvolená možnost", "ar-EG": "الخيار المختار", "zh-CN": "所选选项", "zh-TW": "所選選項" },
  "Chosen options": { "de-DE": "Gewählte Optionen", "fr-FR": "Options choisies", "da-DK": "Valgte tilvalg", "cs-CZ": "Zvolené možnosti", "ar-EG": "الخيارات المختارة", "zh-CN": "所选选项", "zh-TW": "所選選項" },
  "Close for public holidays in a tap, from the kitchen's Hours tab.": { "de-DE": "Mit einem Tipp an Feiertagen schließen, im Tab Öffnungszeiten der Küche.", "fr-FR": "Fermez les jours fériés d’un geste, depuis l’onglet Horaires de la cuisine.", "da-DK": "Luk på helligdage med ét tryk fra køkkenets fane Åbningstider.", "cs-CZ": "Zavřete na státní svátky jedním klepnutím v kartě Otevírací doba v kuchyni.", "ar-EG": "أغلق في العطلات الرسمية بلمسة من تبويب ساعات العمل في المطبخ.", "zh-CN": "在厨房的营业时间页一键设置节假日休息。", "zh-TW": "在廚房的營業時間頁一鍵設定國定假日休息。" },
  "Closed photo": { "de-DE": "Foto bei Geschlossen", "fr-FR": "Photo « fermé »", "da-DK": "Foto ved lukket", "cs-CZ": "Fotka při zavření", "ar-EG": "صورة الإغلاق", "zh-CN": "休息时的照片", "zh-TW": "休息時的照片" },
  "Closes": { "de-DE": "Schließt", "fr-FR": "Fermeture", "da-DK": "Lukker", "cs-CZ": "Zavírá", "ar-EG": "يغلق", "zh-CN": "打烊", "zh-TW": "打烊" },
  "Closure": { "de-DE": "Schließtag", "fr-FR": "Fermeture", "da-DK": "Lukkedag", "cs-CZ": "Zavírací den", "ar-EG": "إغلاق", "zh-CN": "休息日", "zh-TW": "休息日" },
  "Closures": { "de-DE": "Schließtage", "fr-FR": "Fermetures", "da-DK": "Lukkedage", "cs-CZ": "Zavírací dny", "ar-EG": "أيام الإغلاق", "zh-CN": "休息日", "zh-TW": "休息日" },
  "Collected by day": { "de-DE": "Kassiert pro Tag", "fr-FR": "Encaissé par jour", "da-DK": "Opkrævet pr. dag", "cs-CZ": "Vybráno po dnech", "ar-EG": "المحصّل يوميًا", "zh-CN": "每日收款", "zh-TW": "每日收款" },
  "Collected today": { "de-DE": "Heute kassiert", "fr-FR": "Encaissé aujourd’hui", "da-DK": "Opkrævet i dag", "cs-CZ": "Dnes vybráno", "ar-EG": "المحصّل اليوم", "zh-CN": "今日收款", "zh-TW": "今日收款" },
  "Collected, last 7 days": { "de-DE": "Kassiert, letzte 7 Tage", "fr-FR": "Encaissé, 7 derniers jours", "da-DK": "Opkrævet, sidste 7 dage", "cs-CZ": "Vybráno, posledních 7 dní", "ar-EG": "المحصّل، آخر ٧ أيام", "zh-CN": "收款（近 7 天）", "zh-TW": "收款（近 7 天）" },
  "Confirmed": { "de-DE": "Bestätigt", "fr-FR": "Confirmée", "da-DK": "Bekræftet", "cs-CZ": "Potvrzeno", "ar-EG": "مؤكد", "zh-CN": "已确认", "zh-TW": "已確認" },
  "Confirmed by": { "de-DE": "Bestätigt von", "fr-FR": "Confirmée par", "da-DK": "Bekræftet af", "cs-CZ": "Potvrdil(a)", "ar-EG": "أكّده", "zh-CN": "确认人", "zh-TW": "確認人" },
  "Counter photo": { "de-DE": "Foto der Theke", "fr-FR": "Photo du comptoir", "da-DK": "Foto af disken", "cs-CZ": "Fotka pultu", "ar-EG": "صورة الكاونتر", "zh-CN": "柜台照片", "zh-TW": "櫃檯照片" },
  "Created": { "de-DE": "Erstellt", "fr-FR": "Créé", "da-DK": "Oprettet", "cs-CZ": "Vytvořeno", "ar-EG": "أُنشئ", "zh-CN": "创建时间", "zh-TW": "建立時間" },
  "Customer": { "de-DE": "Gast", "fr-FR": "Client", "da-DK": "Gæst", "cs-CZ": "Host", "ar-EG": "الزبون", "zh-CN": "顾客", "zh-TW": "顧客" },
  "Customers": { "de-DE": "Gäste", "fr-FR": "Clients", "da-DK": "Gæster", "cs-CZ": "Hosté", "ar-EG": "الزبائن", "zh-CN": "顾客", "zh-TW": "顧客" },
  "Day": { "de-DE": "Tag", "fr-FR": "Jour", "da-DK": "Dag", "cs-CZ": "Den", "ar-EG": "اليوم", "zh-CN": "日期", "zh-TW": "日期" },
  "Days ahead": { "de-DE": "Tage im Voraus", "fr-FR": "Jours à l’avance", "da-DK": "Dage frem", "cs-CZ": "Dní dopředu", "ar-EG": "أيام مقدمًا", "zh-CN": "提前天数", "zh-TW": "提前天數" },
  "Declined": { "de-DE": "Abgelehnt", "fr-FR": "Refusé", "da-DK": "Afvist", "cs-CZ": "Odmítnuto", "ar-EG": "مرفوض", "zh-CN": "已婉拒", "zh-TW": "已婉拒" },
  "Details deleted": { "de-DE": "Daten gelöscht", "fr-FR": "Données supprimées", "da-DK": "Oplysninger slettet", "cs-CZ": "Údaje smazány", "ar-EG": "حُذفت البيانات", "zh-CN": "信息已删除", "zh-TW": "資料已刪除" },
  "Directions": { "de-DE": "Wegbeschreibung", "fr-FR": "Itinéraire", "da-DK": "Vejvisning", "cs-CZ": "Popis cesty", "ar-EG": "الاتجاهات", "zh-CN": "到店指引", "zh-TW": "到店指引" },
  "Dish": { "de-DE": "Gericht", "fr-FR": "Plat", "da-DK": "Ret", "cs-CZ": "Jídlo", "ar-EG": "الطبق", "zh-CN": "菜品", "zh-TW": "餐點" },
  "Dish name": { "de-DE": "Name des Gerichts", "fr-FR": "Nom du plat", "da-DK": "Rettens navn", "cs-CZ": "Název jídla", "ar-EG": "اسم الطبق", "zh-CN": "菜品名称", "zh-TW": "餐點名稱" },
  "Dishes": { "de-DE": "Gerichte", "fr-FR": "Plats", "da-DK": "Retter", "cs-CZ": "Jídla", "ar-EG": "الأطباق", "zh-CN": "菜品", "zh-TW": "餐點" },
  "Due": { "de-DE": "Fällig", "fr-FR": "Prévu", "da-DK": "Forfalden", "cs-CZ": "Termín", "ar-EG": "المستحق", "zh-CN": "待发送", "zh-TW": "待寄送" },
  "Each": { "de-DE": "Stück", "fr-FR": "L’unité", "da-DK": "Pr. stk.", "cs-CZ": "Za kus", "ar-EG": "للواحد", "zh-CN": "单价", "zh-TW": "單價" },
  "Email": { "de-DE": "E-Mail", "fr-FR": "E-mail", "da-DK": "E-mail", "cs-CZ": "E-mail", "ar-EG": "البريد الإلكتروني", "zh-CN": "电子邮箱", "zh-TW": "電子信箱" },
  "Email a receipt at pickup": { "de-DE": "Beleg bei Abholung per E-Mail", "fr-FR": "Reçu par e-mail au retrait", "da-DK": "Kvittering på mail ved afhentning", "cs-CZ": "Účtenka e-mailem při vyzvednutí", "ar-EG": "إرسال الإيصال بالبريد عند الاستلام", "zh-CN": "取餐时邮件发送收据", "zh-TW": "取餐時郵件寄送收據" },
  "Email a receipt when an order is picked up, and print one from the dashboard.": { "de-DE": "Bei Abholung einen Beleg per E-Mail senden und im Dashboard einen drucken.", "fr-FR": "Envoyez un reçu par e-mail au retrait, et imprimez-en un depuis le tableau de bord.", "da-DK": "Send en kvittering på mail, når en bestilling hentes, og udskriv en fra dashboardet.", "cs-CZ": "Při vyzvednutí pošlete účtenku e-mailem a vytiskněte ji z nástěnky.", "ar-EG": "أرسل إيصالًا بالبريد عند استلام الطلب، واطبع واحدًا من لوحة التحكم.", "zh-CN": "订单取走时邮件发送收据，也可在后台打印。", "zh-TW": "訂單取走時郵件寄送收據，也可在後台列印。" },
  "Email when an order is ready": { "de-DE": "E-Mail, wenn eine Bestellung fertig ist", "fr-FR": "E-mail quand une commande est prête", "da-DK": "Mail, når en bestilling er klar", "cs-CZ": "E-mail, když je objednávka hotová", "ar-EG": "رسالة عند جاهزية الطلب", "zh-CN": "订单做好时发送邮件", "zh-TW": "訂單做好時寄送郵件" },
  "Emails": { "de-DE": "E-Mails", "fr-FR": "E-mails", "da-DK": "Mails", "cs-CZ": "E-maily", "ar-EG": "الرسائل", "zh-CN": "邮件", "zh-TW": "郵件" },
  "Enquiries": { "de-DE": "Anfragen", "fr-FR": "Demandes", "da-DK": "Forespørgsler", "cs-CZ": "Poptávky", "ar-EG": "الاستفسارات", "zh-CN": "询价", "zh-TW": "詢價" },
  "Extra charge": { "de-DE": "Aufpreis", "fr-FR": "Supplément", "da-DK": "Tillæg", "cs-CZ": "Příplatek", "ar-EG": "رسوم إضافية", "zh-CN": "加价", "zh-TW": "加價" },
  "First order": { "de-DE": "Erste Bestellung", "fr-FR": "Première commande", "da-DK": "Første bestilling", "cs-CZ": "První objednávka", "ar-EG": "أول طلب", "zh-CN": "首笔订单", "zh-TW": "首筆訂單" },
  "First order number": { "de-DE": "Erste Bestellnummer", "fr-FR": "Premier numéro de commande", "da-DK": "Første bestillingsnummer", "cs-CZ": "Číslo první objednávky", "ar-EG": "رقم أول طلب", "zh-CN": "首个订单号", "zh-TW": "首個訂單號" },
  "For": { "de-DE": "Für", "fr-FR": "Pour", "da-DK": "Til", "cs-CZ": "Na", "ar-EG": "لـ", "zh-CN": "用于", "zh-TW": "用於" },
  "Friday": { "de-DE": "Freitag", "fr-FR": "Vendredi", "da-DK": "Fredag", "cs-CZ": "Pátek", "ar-EG": "الجمعة", "zh-CN": "星期五", "zh-TW": "星期五" },
  "From": { "de-DE": "Von", "fr-FR": "Du", "da-DK": "Fra", "cs-CZ": "Od", "ar-EG": "من", "zh-CN": "从", "zh-TW": "從" },
  "Front photo": { "de-DE": "Titelfoto", "fr-FR": "Photo principale", "da-DK": "Forsidefoto", "cs-CZ": "Úvodní fotka", "ar-EG": "صورة الواجهة", "zh-CN": "首页照片", "zh-TW": "首頁照片" },
  "Going out": { "de-DE": "Wird gesendet", "fr-FR": "En cours d’envoi", "da-DK": "Sendes", "cs-CZ": "Odesílá se", "ar-EG": "قيد الإرسال", "zh-CN": "发送中", "zh-TW": "寄送中" },
  "Handed over by": { "de-DE": "Übergeben von", "fr-FR": "Remise par", "da-DK": "Udleveret af", "cs-CZ": "Předal(a)", "ar-EG": "سلّمه", "zh-CN": "交付人", "zh-TW": "交付人" },
  "Handled by": { "de-DE": "Bearbeitet von", "fr-FR": "Traité par", "da-DK": "Håndteret af", "cs-CZ": "Vyřídil(a)", "ar-EG": "تولّاه", "zh-CN": "处理人", "zh-TW": "處理人" },
  "Headline": { "de-DE": "Überschrift", "fr-FR": "Titre", "da-DK": "Overskrift", "cs-CZ": "Titulek", "ar-EG": "العنوان الرئيسي", "zh-CN": "标题", "zh-TW": "標題" },
  "Hours": { "de-DE": "Öffnungszeiten", "fr-FR": "Horaires", "da-DK": "Åbningstider", "cs-CZ": "Otevírací doba", "ar-EG": "ساعات العمل", "zh-CN": "营业时间", "zh-TW": "營業時間" },
  "Introduction": { "de-DE": "Einleitung", "fr-FR": "Introduction", "da-DK": "Introduktion", "cs-CZ": "Úvod", "ar-EG": "المقدمة", "zh-CN": "介绍", "zh-TW": "介紹" },
  "Items": { "de-DE": "Artikel", "fr-FR": "Articles", "da-DK": "Varer", "cs-CZ": "Položky", "ar-EG": "العناصر", "zh-CN": "件数", "zh-TW": "件數" },
  "Items per online order": { "de-DE": "Artikel pro Online-Bestellung", "fr-FR": "Articles par commande en ligne", "da-DK": "Varer pr. onlinebestilling", "cs-CZ": "Položek na online objednávku", "ar-EG": "العناصر لكل طلب عبر الإنترنت", "zh-CN": "每笔在线订单件数", "zh-TW": "每筆線上訂單件數" },
  "Kind": { "de-DE": "Art", "fr-FR": "Type", "da-DK": "Type", "cs-CZ": "Druh", "ar-EG": "النوع", "zh-CN": "类型", "zh-TW": "類型" },
  "Kitchen": { "de-DE": "Küche", "fr-FR": "Cuisine", "da-DK": "Køkken", "cs-CZ": "Kuchyně", "ar-EG": "المطبخ", "zh-CN": "厨房", "zh-TW": "廚房" },
  "Kitchen note": { "de-DE": "Notiz der Küche", "fr-FR": "Note de la cuisine", "da-DK": "Køkkenets note", "cs-CZ": "Poznámka kuchyně", "ar-EG": "ملاحظة المطبخ", "zh-CN": "厨房备注", "zh-TW": "廚房備註" },
  "Kitchen settings": { "de-DE": "Küchen-Einstellungen", "fr-FR": "Réglages de la cuisine", "da-DK": "Køkkenets indstillinger", "cs-CZ": "Nastavení kuchyně", "ar-EG": "إعدادات المطبخ", "zh-CN": "厨房设置", "zh-TW": "廚房設定" },
  "Language": { "de-DE": "Sprache", "fr-FR": "Langue", "da-DK": "Sprog", "cs-CZ": "Jazyk", "ar-EG": "اللغة", "zh-CN": "语言", "zh-TW": "語言" },
  "Large order": { "de-DE": "Großbestellung", "fr-FR": "Grande commande", "da-DK": "Stor bestilling", "cs-CZ": "Velká objednávka", "ar-EG": "طلب كبير", "zh-CN": "团体订餐", "zh-TW": "團體訂餐" },
  "Large order enquiry received": { "de-DE": "Anfrage für Großbestellung erhalten", "fr-FR": "Demande de grande commande reçue", "da-DK": "Forespørgsel om stor bestilling modtaget", "cs-CZ": "Poptávka velké objednávky přijata", "ar-EG": "استُلم استفسار طلب كبير", "zh-CN": "已收到大额订单询价", "zh-TW": "已收到大量訂購詢價" },
  "Large orders": { "de-DE": "Großbestellungen", "fr-FR": "Grandes commandes", "da-DK": "Store bestillinger", "cs-CZ": "Velké objednávky", "ar-EG": "الطلبات الكبيرة", "zh-CN": "团体订餐", "zh-TW": "團體訂餐" },
  "Line total": { "de-DE": "Zeilensumme", "fr-FR": "Total de la ligne", "da-DK": "Linjetotal", "cs-CZ": "Součet položky", "ar-EG": "إجمالي البند", "zh-CN": "小计", "zh-TW": "小計" },
  "Link code": { "de-DE": "Link-Code", "fr-FR": "Code du lien", "da-DK": "Linkkode", "cs-CZ": "Kód odkazu", "ar-EG": "رمز الرابط", "zh-CN": "链接代码", "zh-TW": "連結代碼" },
  "Link stopped": { "de-DE": "Link gestoppt", "fr-FR": "Lien désactivé", "da-DK": "Link stoppet", "cs-CZ": "Odkaz zastaven", "ar-EG": "الرابط متوقف", "zh-CN": "链接已停用", "zh-TW": "連結已停用" },
  "Link works until": { "de-DE": "Link gültig bis", "fr-FR": "Lien valable jusqu’au", "da-DK": "Linket virker til", "cs-CZ": "Odkaz platí do", "ar-EG": "الرابط صالح حتى", "zh-CN": "链接有效期至", "zh-TW": "連結有效至" },
  "Manage": { "de-DE": "Verwalten", "fr-FR": "Gérer", "da-DK": "Administrer", "cs-CZ": "Spravovat", "ar-EG": "إدارة", "zh-CN": "管理", "zh-TW": "管理" },
  "Marked not collected": { "de-DE": "Als nicht abgeholt markiert", "fr-FR": "Marquée non retirée", "da-DK": "Markeret som ikke hentet", "cs-CZ": "Označeno jako nevyzvednuté", "ar-EG": "عُلّم كغير مستلم", "zh-CN": "标记为未取餐", "zh-TW": "標記為未取餐" },
  "Menu": { "de-DE": "Speisekarte", "fr-FR": "La carte", "da-DK": "Menukort", "cs-CZ": "Jídelní lístek", "ar-EG": "القائمة", "zh-CN": "菜单", "zh-TW": "菜單" },
  "Messages": { "de-DE": "Nachrichten", "fr-FR": "Messages", "da-DK": "Beskeder", "cs-CZ": "Zprávy", "ar-EG": "الرسائل", "zh-CN": "消息", "zh-TW": "訊息" },
  "Minutes of notice": { "de-DE": "Minuten Vorlauf", "fr-FR": "Minutes de préavis", "da-DK": "Minutters varsel", "cs-CZ": "Minut předem", "ar-EG": "دقائق الإشعار المسبق", "zh-CN": "提前通知分钟数", "zh-TW": "提前通知分鐘數" },
  "Minutes per pickup slot": { "de-DE": "Minuten pro Abholzeit", "fr-FR": "Minutes par créneau de retrait", "da-DK": "Minutter pr. afhentningstid", "cs-CZ": "Minut na čas vyzvednutí", "ar-EG": "دقائق لكل موعد استلام", "zh-CN": "每个取餐时段分钟数", "zh-TW": "每個取餐時段分鐘數" },
  "Minutes to prepare": { "de-DE": "Minuten Zubereitung", "fr-FR": "Minutes de préparation", "da-DK": "Minutters tilberedning", "cs-CZ": "Minut přípravy", "ar-EG": "دقائق التحضير", "zh-CN": "准备分钟数", "zh-TW": "準備分鐘數" },
  "Monday": { "de-DE": "Montag", "fr-FR": "Lundi", "da-DK": "Mandag", "cs-CZ": "Pondělí", "ar-EG": "الاثنين", "zh-CN": "星期一", "zh-TW": "星期一" },
  "Name": { "de-DE": "Name", "fr-FR": "Nom", "da-DK": "Navn", "cs-CZ": "Jméno", "ar-EG": "الاسم", "zh-CN": "姓名", "zh-TW": "姓名" },
  "New": { "de-DE": "Neu", "fr-FR": "Nouvelle", "da-DK": "Ny", "cs-CZ": "Nová", "ar-EG": "جديد", "zh-CN": "新订单", "zh-TW": "新訂單" },
  "No longer needed": { "de-DE": "Nicht mehr nötig", "fr-FR": "Plus nécessaire", "da-DK": "Ikke længere nødvendig", "cs-CZ": "Už není potřeba", "ar-EG": "لم يعد مطلوبًا", "zh-CN": "已无需发送", "zh-TW": "已無需寄送" },
  "Not collected": { "de-DE": "Nicht abgeholt", "fr-FR": "Non retirée", "da-DK": "Ikke hentet", "cs-CZ": "Nevyzvednuto", "ar-EG": "لم يُستلم", "zh-CN": "未取餐", "zh-TW": "未取餐" },
  "Not ready by closing": { "de-DE": "Bis Ladenschluss nicht fertig", "fr-FR": "Pas prête avant la fermeture", "da-DK": "Ikke klar før lukketid", "cs-CZ": "Nehotové do zavírací doby", "ar-EG": "لم يجهز قبل الإغلاق", "zh-CN": "打烊前未做好", "zh-TW": "打烊前未做好" },
  "Not sent": { "de-DE": "Nicht gesendet", "fr-FR": "Non envoyé", "da-DK": "Ikke sendt", "cs-CZ": "Neodesláno", "ar-EG": "لم يُرسل", "zh-CN": "未发送", "zh-TW": "未寄送" },
  "Note": { "de-DE": "Notiz", "fr-FR": "Note", "da-DK": "Note", "cs-CZ": "Poznámka", "ar-EG": "ملاحظة", "zh-CN": "备注", "zh-TW": "備註" },
  "Note for the kitchen": { "de-DE": "Notiz für die Küche", "fr-FR": "Note pour la cuisine", "da-DK": "Note til køkkenet", "cs-CZ": "Poznámka pro kuchyni", "ar-EG": "ملاحظة للمطبخ", "zh-CN": "给厨房的备注", "zh-TW": "給廚房的備註" },
  "Number": { "de-DE": "Nummer", "fr-FR": "Numéro", "da-DK": "Nummer", "cs-CZ": "Číslo", "ar-EG": "الرقم", "zh-CN": "编号", "zh-TW": "編號" },
  "Number (running)": { "de-DE": "Nummer (fortlaufend)", "fr-FR": "Numéro (séquence)", "da-DK": "Nummer (løbende)", "cs-CZ": "Číslo (pořadové)", "ar-EG": "الرقم (تسلسلي)", "zh-CN": "编号（流水）", "zh-TW": "編號（流水）" },
  "On": { "de-DE": "Am", "fr-FR": "Le", "da-DK": "Den", "cs-CZ": "Dne", "ar-EG": "في", "zh-CN": "日期", "zh-TW": "日期" },
  "Online": { "de-DE": "Online", "fr-FR": "En ligne", "da-DK": "Online", "cs-CZ": "Online", "ar-EG": "عبر الإنترنت", "zh-CN": "在线", "zh-TW": "線上" },
  "Open": { "de-DE": "Geöffnet", "fr-FR": "Ouvert", "da-DK": "Åben", "cs-CZ": "Otevřeno", "ar-EG": "مفتوح", "zh-CN": "营业", "zh-TW": "營業" },
  "Opening hours": { "de-DE": "Öffnungszeiten", "fr-FR": "Heures d’ouverture", "da-DK": "Åbningstider", "cs-CZ": "Otevírací doba", "ar-EG": "ساعات العمل", "zh-CN": "营业时间", "zh-TW": "營業時間" },
  "Opens": { "de-DE": "Öffnet", "fr-FR": "Ouverture", "da-DK": "Åbner", "cs-CZ": "Otevírá", "ar-EG": "يفتح", "zh-CN": "开门", "zh-TW": "開門" },
  "Option": { "de-DE": "Option", "fr-FR": "Option", "da-DK": "Tilvalg", "cs-CZ": "Možnost", "ar-EG": "خيار", "zh-CN": "选项", "zh-TW": "選項" },
  "Option groups": { "de-DE": "Optionsgruppen", "fr-FR": "Groupes d’options", "da-DK": "Tilvalgsgrupper", "cs-CZ": "Skupiny možností", "ar-EG": "مجموعات الخيارات", "zh-CN": "选项组", "zh-TW": "選項組" },
  "Option name": { "de-DE": "Name der Option", "fr-FR": "Nom de l’option", "da-DK": "Tilvalgets navn", "cs-CZ": "Název možnosti", "ar-EG": "اسم الخيار", "zh-CN": "选项名称", "zh-TW": "選項名稱" },
  "Options": { "de-DE": "Optionen", "fr-FR": "Options", "da-DK": "Tilvalg", "cs-CZ": "Možnosti", "ar-EG": "الخيارات", "zh-CN": "选项", "zh-TW": "選項" },
  "Order": { "de-DE": "Bestellung", "fr-FR": "Commande", "da-DK": "Bestilling", "cs-CZ": "Objednávka", "ar-EG": "الطلب", "zh-CN": "订单", "zh-TW": "訂單" },
  "Order confirmation": { "de-DE": "Bestellbestätigung", "fr-FR": "Confirmation de commande", "da-DK": "Ordrebekræftelse", "cs-CZ": "Potvrzení objednávky", "ar-EG": "تأكيد الطلب", "zh-CN": "订单确认", "zh-TW": "訂單確認" },
  "Order confirmation (phone)": { "de-DE": "Bestellbestätigung (Telefon)", "fr-FR": "Confirmation de commande (téléphone)", "da-DK": "Ordrebekræftelse (telefon)", "cs-CZ": "Potvrzení objednávky (telefon)", "ar-EG": "تأكيد الطلب (هاتفي)", "zh-CN": "订单确认（电话）", "zh-TW": "訂單確認（電話）" },
  "Order line": { "de-DE": "Bestellposition", "fr-FR": "Ligne de commande", "da-DK": "Bestillingslinje", "cs-CZ": "Položka objednávky", "ar-EG": "بند الطلب", "zh-CN": "订单明细", "zh-TW": "訂單明細" },
  "Order lines": { "de-DE": "Bestellpositionen", "fr-FR": "Lignes de commande", "da-DK": "Bestillingslinjer", "cs-CZ": "Položky objednávky", "ar-EG": "بنود الطلب", "zh-CN": "订单明细", "zh-TW": "訂單明細" },
  "Order ready": { "de-DE": "Bestellung fertig", "fr-FR": "Commande prête", "da-DK": "Bestilling klar", "cs-CZ": "Objednávka hotová", "ar-EG": "الطلب جاهز", "zh-CN": "订单已完成", "zh-TW": "訂單已完成" },
  "Orders": { "de-DE": "Bestellungen", "fr-FR": "Commandes", "da-DK": "Bestillinger", "cs-CZ": "Objednávky", "ar-EG": "الطلبات", "zh-CN": "订单", "zh-TW": "訂單" },
  "Orders by day": { "de-DE": "Bestellungen pro Tag", "fr-FR": "Commandes par jour", "da-DK": "Bestillinger pr. dag", "cs-CZ": "Objednávky po dnech", "ar-EG": "الطلبات يوميًا", "zh-CN": "每日订单", "zh-TW": "每日訂單" },
  "Orders per slot": { "de-DE": "Bestellungen pro Abholzeit", "fr-FR": "Commandes par créneau", "da-DK": "Bestillinger pr. tidspunkt", "cs-CZ": "Objednávek na čas", "ar-EG": "الطلبات لكل موعد", "zh-CN": "每个时段订单数", "zh-TW": "每個時段訂單數" },
  "Orders today": { "de-DE": "Bestellungen heute", "fr-FR": "Commandes aujourd’hui", "da-DK": "Bestillinger i dag", "cs-CZ": "Dnešní objednávky", "ar-EG": "طلبات اليوم", "zh-CN": "今日订单", "zh-TW": "今日訂單" },
  "Orders, last 7 days": { "de-DE": "Bestellungen, letzte 7 Tage", "fr-FR": "Commandes, 7 derniers jours", "da-DK": "Bestillinger, sidste 7 dage", "cs-CZ": "Objednávky, posledních 7 dní", "ar-EG": "الطلبات، آخر ٧ أيام", "zh-CN": "订单（近 7 天）", "zh-TW": "訂單（近 7 天）" },
  "Other": { "de-DE": "Sonstiges", "fr-FR": "Autre", "da-DK": "Andet", "cs-CZ": "Jiné", "ar-EG": "أخرى", "zh-CN": "其他", "zh-TW": "其他" },
  "Overview": { "de-DE": "Übersicht", "fr-FR": "Vue d’ensemble", "da-DK": "Overblik", "cs-CZ": "Přehled", "ar-EG": "نظرة عامة", "zh-CN": "概览", "zh-TW": "概覽" },
  "Paid": { "de-DE": "Bezahlt", "fr-FR": "Payé", "da-DK": "Betalt", "cs-CZ": "Zaplaceno", "ar-EG": "مدفوع", "zh-CN": "已付款", "zh-TW": "已付款" },
  "Paid by": { "de-DE": "Bezahlt mit", "fr-FR": "Payé par", "da-DK": "Betalt med", "cs-CZ": "Zaplaceno", "ar-EG": "دُفع بـ", "zh-CN": "付款方式", "zh-TW": "付款方式" },
  "Paused": { "de-DE": "Pausiert", "fr-FR": "En pause", "da-DK": "På pause", "cs-CZ": "Pozastaveno", "ar-EG": "متوقف مؤقتًا", "zh-CN": "已暂停", "zh-TW": "已暫停" },
  "Paused at": { "de-DE": "Pausiert um", "fr-FR": "Mis en pause à", "da-DK": "Sat på pause kl.", "cs-CZ": "Pozastaveno v", "ar-EG": "أُوقف في", "zh-CN": "暂停时间", "zh-TW": "暫停時間" },
  "Paused by": { "de-DE": "Pausiert von", "fr-FR": "Mis en pause par", "da-DK": "Sat på pause af", "cs-CZ": "Pozastavil(a)", "ar-EG": "أوقفه", "zh-CN": "暂停人", "zh-TW": "暫停人" },
  "Paused slot": { "de-DE": "Pausierte Abholzeit", "fr-FR": "Créneau en pause", "da-DK": "Tidspunkt på pause", "cs-CZ": "Pozastavený čas", "ar-EG": "موعد متوقف", "zh-CN": "已暂停时段", "zh-TW": "已暫停時段" },
  "Paused slots": { "de-DE": "Pausierte Abholzeiten", "fr-FR": "Créneaux en pause", "da-DK": "Tidspunkter på pause", "cs-CZ": "Pozastavené časy", "ar-EG": "المواعيد المتوقفة", "zh-CN": "已暂停时段", "zh-TW": "已暫停時段" },
  "People": { "de-DE": "Personen", "fr-FR": "Personnes", "da-DK": "Personer", "cs-CZ": "Osoby", "ar-EG": "الأشخاص", "zh-CN": "人数", "zh-TW": "人數" },
  "Phone": { "de-DE": "Telefon", "fr-FR": "Téléphone", "da-DK": "Telefon", "cs-CZ": "Telefon", "ar-EG": "الهاتف", "zh-CN": "电话", "zh-TW": "電話" },
  "Picked up": { "de-DE": "Abgeholt", "fr-FR": "Retirée", "da-DK": "Hentet", "cs-CZ": "Vyzvednuto", "ar-EG": "تم الاستلام", "zh-CN": "已取餐", "zh-TW": "已取餐" },
  "Pickup": { "de-DE": "Abholung", "fr-FR": "Retrait", "da-DK": "Afhentning", "cs-CZ": "Vyzvednutí", "ar-EG": "الاستلام", "zh-CN": "取餐", "zh-TW": "取餐" },
  "Placed": { "de-DE": "Aufgegeben", "fr-FR": "Passée", "da-DK": "Afgivet", "cs-CZ": "Odesláno", "ar-EG": "مقدَّم", "zh-CN": "下单时间", "zh-TW": "下單時間" },
  "Portions": { "de-DE": "Portionen", "fr-FR": "Portions", "da-DK": "Portioner", "cs-CZ": "Porce", "ar-EG": "الحصص", "zh-CN": "份数", "zh-TW": "份數" },
  "Portions for": { "de-DE": "Portionen für", "fr-FR": "Portions pour", "da-DK": "Portioner til", "cs-CZ": "Porce na", "ar-EG": "الحصص ليوم", "zh-CN": "份数适用日期", "zh-TW": "份數適用日期" },
  "Position": { "de-DE": "Position", "fr-FR": "Position", "da-DK": "Placering", "cs-CZ": "Pořadí", "ar-EG": "الترتيب", "zh-CN": "排序", "zh-TW": "排序" },
  "Preparing": { "de-DE": "In Zubereitung", "fr-FR": "En préparation", "da-DK": "Tilberedes", "cs-CZ": "Připravuje se", "ar-EG": "قيد التحضير", "zh-CN": "制作中", "zh-TW": "製作中" },
  "Price": { "de-DE": "Preis", "fr-FR": "Prix", "da-DK": "Pris", "cs-CZ": "Cena", "ar-EG": "السعر", "zh-CN": "价格", "zh-TW": "價格" },
  "Public holidays as closures": { "de-DE": "Feiertage als Schließtage", "fr-FR": "Jours fériés comme fermetures", "da-DK": "Helligdage som lukkedage", "cs-CZ": "Státní svátky jako zavírací dny", "ar-EG": "العطلات الرسمية كأيام إغلاق", "zh-CN": "节假日作为休息日", "zh-TW": "國定假日作為休息日" },
  "Quantity": { "de-DE": "Menge", "fr-FR": "Quantité", "da-DK": "Antal", "cs-CZ": "Množství", "ar-EG": "الكمية", "zh-CN": "数量", "zh-TW": "數量" },
  "Ready": { "de-DE": "Fertig", "fr-FR": "Prête", "da-DK": "Klar", "cs-CZ": "Hotovo", "ar-EG": "جاهز", "zh-CN": "已做好", "zh-TW": "已做好" },
  "Ready by": { "de-DE": "Fertig von", "fr-FR": "Prête par", "da-DK": "Klar af", "cs-CZ": "Hotovo –", "ar-EG": "جهّزه", "zh-CN": "完成人", "zh-TW": "完成人" },
  "Reason": { "de-DE": "Grund", "fr-FR": "Raison", "da-DK": "Årsag", "cs-CZ": "Důvod", "ar-EG": "السبب", "zh-CN": "原因", "zh-TW": "原因" },
  "Receipt": { "de-DE": "Beleg", "fr-FR": "Reçu", "da-DK": "Kvittering", "cs-CZ": "Účtenka", "ar-EG": "الإيصال", "zh-CN": "收据", "zh-TW": "收據" },
  "Receipts": { "de-DE": "Belege", "fr-FR": "Reçus", "da-DK": "Kvitteringer", "cs-CZ": "Účtenky", "ar-EG": "الإيصالات", "zh-CN": "收据", "zh-TW": "收據" },
  "Reference": { "de-DE": "Referenz", "fr-FR": "Référence", "da-DK": "Reference", "cs-CZ": "Číslo poptávky", "ar-EG": "المرجع", "zh-CN": "编号", "zh-TW": "編號" },
  "Reference (running)": { "de-DE": "Referenz (fortlaufend)", "fr-FR": "Référence (séquence)", "da-DK": "Reference (løbende)", "cs-CZ": "Číslo poptávky (pořadové)", "ar-EG": "المرجع (تسلسلي)", "zh-CN": "编号（流水）", "zh-TW": "編號（流水）" },
  "Retry key": { "de-DE": "Wiederholungsschlüssel", "fr-FR": "Clé de nouvel essai", "da-DK": "Genforsøgsnøgle", "cs-CZ": "Klíč opakování", "ar-EG": "مفتاح إعادة المحاولة", "zh-CN": "重试密钥", "zh-TW": "重試金鑰" },
  "Saturday": { "de-DE": "Samstag", "fr-FR": "Samedi", "da-DK": "Lørdag", "cs-CZ": "Sobota", "ar-EG": "السبت", "zh-CN": "星期六", "zh-TW": "星期六" },
  "Sent": { "de-DE": "Gesendet", "fr-FR": "Envoyé", "da-DK": "Sendt", "cs-CZ": "Odesláno", "ar-EG": "أُرسل", "zh-CN": "已发送", "zh-TW": "已寄送" },
  "Settings": { "de-DE": "Einstellungen", "fr-FR": "Réglages", "da-DK": "Indstillinger", "cs-CZ": "Nastavení", "ar-EG": "الإعدادات", "zh-CN": "设置", "zh-TW": "設定" },
  "Skipped": { "de-DE": "Übersprungen", "fr-FR": "Ignoré", "da-DK": "Sprunget over", "cs-CZ": "Přeskočeno", "ar-EG": "تم التخطي", "zh-CN": "已跳过", "zh-TW": "已略過" },
  "Skipped by hand": { "de-DE": "Von Hand übersprungen", "fr-FR": "Ignoré manuellement", "da-DK": "Sprunget over manuelt", "cs-CZ": "Přeskočeno ručně", "ar-EG": "تُخطّي يدويًا", "zh-CN": "手动跳过", "zh-TW": "手動略過" },
  "Slot": { "de-DE": "Abholzeit", "fr-FR": "Créneau", "da-DK": "Tidspunkt", "cs-CZ": "Čas", "ar-EG": "الموعد", "zh-CN": "时段", "zh-TW": "時段" },
  "Sold online": { "de-DE": "Online verkauft", "fr-FR": "Vendu en ligne", "da-DK": "Sælges online", "cs-CZ": "Prodává se online", "ar-EG": "يُباع عبر الإنترنت", "zh-CN": "在线销售", "zh-TW": "線上販售" },
  "Something ran out": { "de-DE": "Etwas ist ausgegangen", "fr-FR": "Un produit a manqué", "da-DK": "Noget slap op", "cs-CZ": "Něco došlo", "ar-EG": "نفد شيء", "zh-CN": "有食材用完了", "zh-TW": "有食材用完了" },
  "Started": { "de-DE": "Begonnen", "fr-FR": "Commencée", "da-DK": "Startet", "cs-CZ": "Zahájeno", "ar-EG": "بدأ", "zh-CN": "已开始", "zh-TW": "已開始" },
  "Status": { "de-DE": "Status", "fr-FR": "Statut", "da-DK": "Status", "cs-CZ": "Stav", "ar-EG": "الحالة", "zh-CN": "状态", "zh-TW": "狀態" },
  "Still to collect today": { "de-DE": "Heute noch zu kassieren", "fr-FR": "Reste à encaisser aujourd’hui", "da-DK": "Mangler at blive opkrævet i dag", "cs-CZ": "Dnes ještě k vybrání", "ar-EG": "المتبقي للتحصيل اليوم", "zh-CN": "今日待收款", "zh-TW": "今日待收款" },
  "Street photo": { "de-DE": "Straßenfoto", "fr-FR": "Photo de la rue", "da-DK": "Gadefoto", "cs-CZ": "Fotka ulice", "ar-EG": "صورة الشارع", "zh-CN": "街景照片", "zh-TW": "街景照片" },
  "Subtotal": { "de-DE": "Zwischensumme", "fr-FR": "Sous-total", "da-DK": "Subtotal", "cs-CZ": "Mezisoučet", "ar-EG": "المجموع الفرعي", "zh-CN": "小计", "zh-TW": "小計" },
  "Sunday": { "de-DE": "Sonntag", "fr-FR": "Dimanche", "da-DK": "Søndag", "cs-CZ": "Neděle", "ar-EG": "الأحد", "zh-CN": "星期日", "zh-TW": "星期日" },
  "Taken": { "de-DE": "Belegt", "fr-FR": "Pris", "da-DK": "Optaget", "cs-CZ": "Obsazeno", "ar-EG": "محجوز", "zh-CN": "已订", "zh-TW": "已訂" },
  "Taking online orders": { "de-DE": "Online-Bestellungen annehmen", "fr-FR": "Commandes en ligne acceptées", "da-DK": "Tager imod onlinebestillinger", "cs-CZ": "Přijímat online objednávky", "ar-EG": "استقبال الطلبات عبر الإنترنت", "zh-CN": "接受在线订单", "zh-TW": "接受線上訂單" },
  "Tax": { "de-DE": "Steuer", "fr-FR": "Taxe", "da-DK": "Moms", "cs-CZ": "Daň", "ar-EG": "الضريبة", "zh-CN": "税费", "zh-TW": "稅金" },
  "Tax rate (%)": { "de-DE": "Steuersatz (%)", "fr-FR": "Taux de taxe (%)", "da-DK": "Momssats (%)", "cs-CZ": "Sazba daně (%)", "ar-EG": "نسبة الضريبة (%)", "zh-CN": "税率 (%)", "zh-TW": "稅率 (%)" },
  "The customer asked": { "de-DE": "Auf Wunsch des Gasts", "fr-FR": "À la demande du client", "da-DK": "Gæsten bad om det", "cs-CZ": "Na přání hosta", "ar-EG": "بطلب من الزبون", "zh-CN": "顾客要求", "zh-TW": "顧客要求" },
  "The kitchen was too busy": { "de-DE": "Die Küche war zu voll", "fr-FR": "La cuisine était trop chargée", "da-DK": "Køkkenet havde for travlt", "cs-CZ": "Kuchyně byla přetížená", "ar-EG": "كان المطبخ مشغولًا جدًا", "zh-CN": "厨房太忙", "zh-TW": "廚房太忙" },
  "Thursday": { "de-DE": "Donnerstag", "fr-FR": "Jeudi", "da-DK": "Torsdag", "cs-CZ": "Čtvrtek", "ar-EG": "الخميس", "zh-CN": "星期四", "zh-TW": "星期四" },
  "Tile colour": { "de-DE": "Kachelfarbe", "fr-FR": "Couleur de la vignette", "da-DK": "Flisefarve", "cs-CZ": "Barva dlaždice", "ar-EG": "لون البطاقة", "zh-CN": "卡片颜色", "zh-TW": "卡片顏色" },
  "To": { "de-DE": "Bis", "fr-FR": "Au", "da-DK": "Til", "cs-CZ": "Do", "ar-EG": "إلى", "zh-CN": "至", "zh-TW": "至" },
  "Total": { "de-DE": "Gesamt", "fr-FR": "Total", "da-DK": "I alt", "cs-CZ": "Celkem", "ar-EG": "الإجمالي", "zh-CN": "合计", "zh-TW": "合計" },
  "Tuesday": { "de-DE": "Dienstag", "fr-FR": "Mardi", "da-DK": "Tirsdag", "cs-CZ": "Úterý", "ar-EG": "الثلاثاء", "zh-CN": "星期二", "zh-TW": "星期二" },
  "Void": { "de-DE": "Ungültig", "fr-FR": "Annulé", "da-DK": "Ugyldig", "cs-CZ": "Neplatné", "ar-EG": "ملغى", "zh-CN": "已作废", "zh-TW": "已作廢" },
  "Wednesday": { "de-DE": "Mittwoch", "fr-FR": "Mercredi", "da-DK": "Onsdag", "cs-CZ": "Středa", "ar-EG": "الأربعاء", "zh-CN": "星期三", "zh-TW": "星期三" },
  "What ran out": { "de-DE": "Was ausgegangen ist", "fr-FR": "Ce qui a manqué", "da-DK": "Hvad der slap op", "cs-CZ": "Co došlo", "ar-EG": "ما الذي نفد", "zh-CN": "用完的食材", "zh-TW": "用完的食材" },
  "What they asked": { "de-DE": "Was angefragt wurde", "fr-FR": "Ce qui a été demandé", "da-DK": "Hvad de spurgte om", "cs-CZ": "Co poptali", "ar-EG": "ما طلبوه", "zh-CN": "询价内容", "zh-TW": "詢價內容" },
  "What went wrong": { "de-DE": "Was schiefging", "fr-FR": "Ce qui n’a pas fonctionné", "da-DK": "Hvad der gik galt", "cs-CZ": "Co se pokazilo", "ar-EG": "ما الخطأ", "zh-CN": "出错原因", "zh-TW": "出錯原因" },
  "Why it was cancelled": { "de-DE": "Warum storniert", "fr-FR": "Motif d’annulation", "da-DK": "Hvorfor den blev annulleret", "cs-CZ": "Proč bylo zrušeno", "ar-EG": "سبب الإلغاء", "zh-CN": "取消原因", "zh-TW": "取消原因" },
  "Why it was skipped": { "de-DE": "Warum übersprungen", "fr-FR": "Motif de l’omission", "da-DK": "Hvorfor den blev sprunget over", "cs-CZ": "Proč bylo přeskočeno", "ar-EG": "سبب التخطي", "zh-CN": "跳过原因", "zh-TW": "略過原因" },
};
