/**
 * The design's icons (Lucide), by the names the design gives them. Each is
 * drawn aria-hidden: the words beside it carry its meaning.
 */
import {
  AlertCircle,
  AppWindow,
  ArrowLeft,
  ArrowRight,
  Banknote,
  Bell,
  BellRing,
  Calendar,
  CalendarDays,
  CalendarHeart,
  CalendarX,
  Check,
  CheckCircle2,
  ChefHat,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleSlash,
  ClipboardCheck,
  Clock,
  Cookie,
  CreditCard,
  CupSoda,
  DoorClosed,
  FastForward,
  Flame,
  Globe,
  HandPlatter,
  Home,
  Hourglass,
  House,
  Info,
  KeyRound,
  Languages,
  LayoutList,
  Leaf,
  Link,
  Link2Off,
  List,
  ListChecks,
  LogIn,
  LogOut,
  Mail,
  MailOpen,
  MailSearch,
  MapPin,
  Menu,
  MessageSquare,
  Minus,
  MonitorSmartphone,
  Moon,
  PackageX,
  Pause,
  Pencil,
  Phone,
  PhoneCall,
  PhoneIncoming,
  Pizza,
  Play,
  Plus,
  Power,
  PowerOff,
  Printer,
  Radar,
  Receipt,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Salad,
  ScanLine,
  Send,
  ShieldAlert,
  ShoppingBag,
  SlidersHorizontal,
  Soup,
  Sun,
  Sunrise,
  Tag,
  Timer,
  TimerOff,
  Trash2,
  TriangleAlert,
  UserRound,
  Users,
  Utensils,
  Volume2,
  VolumeX,
  Wallet,
  WandSparkles,
  WifiOff,
  X,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  "alert-circle": AlertCircle,
  "app-window": AppWindow,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "banknote": Banknote,
  "bell": Bell,
  "bell-ring": BellRing,
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "calendar-heart": CalendarHeart,
  "calendar-x": CalendarX,
  "check": Check,
  "check-circle-2": CheckCircle2,
  "chef-hat": ChefHat,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-slash": CircleSlash,
  "clipboard-check": ClipboardCheck,
  "clock": Clock,
  "cookie": Cookie,
  "credit-card": CreditCard,
  "cup-soda": CupSoda,
  "door-closed": DoorClosed,
  "fast-forward": FastForward,
  "flame": Flame,
  "globe": Globe,
  "hand-platter": HandPlatter,
  "home": Home,
  "hourglass": Hourglass,
  "house": House,
  "info": Info,
  "key-round": KeyRound,
  "languages": Languages,
  "layout-list": LayoutList,
  "leaf": Leaf,
  "link": Link,
  "link-2-off": Link2Off,
  "list": List,
  "list-checks": ListChecks,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "mail-open": MailOpen,
  "mail-search": MailSearch,
  "map-pin": MapPin,
  "menu": Menu,
  "message-square": MessageSquare,
  "minus": Minus,
  "monitor-smartphone": MonitorSmartphone,
  "moon": Moon,
  "package-x": PackageX,
  "pause": Pause,
  "pencil": Pencil,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-incoming": PhoneIncoming,
  "pizza": Pizza,
  "play": Play,
  "plus": Plus,
  "power": Power,
  "power-off": PowerOff,
  "printer": Printer,
  "radar": Radar,
  "receipt": Receipt,
  "receipt-text": ReceiptText,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "salad": Salad,
  "scan-line": ScanLine,
  "send": Send,
  "shield-alert": ShieldAlert,
  "shopping-bag": ShoppingBag,
  "sliders-horizontal": SlidersHorizontal,
  "soup": Soup,
  "sun": Sun,
  "sunrise": Sunrise,
  "tag": Tag,
  "timer": Timer,
  "timer-off": TimerOff,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "user-round": UserRound,
  "users": Users,
  "utensils": Utensils,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "wallet": Wallet,
  "wand-sparkles": WandSparkles,
  "wifi-off": WifiOff,
  "x": X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 16, stroke, className, style }: { name: IconName; size?: number; stroke?: number; className?: string; style?: React.CSSProperties }) {
  const Drawn = ICONS[name];
  return <Drawn aria-hidden="true" focusable="false" width={size} height={size} strokeWidth={stroke ?? 2} className={className === undefined ? "jk-icon" : `jk-icon ${className}`} style={{ flex: "none", ...style }} />;
}
